services:
  WebApp:
    container_name: aoame-webapp-container
    #build: ./webapp
    image: iisresearch/aoame-webapp-image:latest
    depends_on:
      - WebService
    ports:
      - 4200:4200
    networks:
        - aoame-network

  WebService:
    container_name: aoame-webservice-container
    #build: ./webservice
    image: iisresearch/aoame-webservice-image:latest
    environment:
      - TRIPLESTORE_ENDPOINT=http://JenaFuseki:3030/ModEnv
    depends_on:
      - JenaFuseki
    ports:
      - 8080:8080
    networks:
      - aoame-network

  JenaFuseki:
    container_name: jena-fuseki-container
    #build: ./jena-fuseki
    image: iisresearch/jena-fuseki-image:latest
    ports:
      - 3030:3030
    networks:
      - aoame-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3030" ]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  aoame-network:
    driver: bridge
