services:
  webapp:
    container_name: aoame-webapp-container
    build: ./aoame/OntologyBasedModellingEnvironment-WebApp
    #image: iisresearch/aoame-webapp-image:latest
    develop:
        watch:
          - action: rebuild
            path: ./aoame/OntologyBasedModellingEnvironment-WebApp/
            target: /app
          - action: rebuild
            path: ./aoame/OntologyBasedModellingEnvironment-WebApp/package.json
    depends_on:
      - webservice
    ports:
      - 4200:4200
    networks:
        - aoame-network

  webservice:
    container_name: aoame-webservice-container
    build: ./aoame/OntologyBasedModellingEnvironment-WebService
    #image: iisresearch/aoame-webservice-image:latest
    develop:
      watch:
        - action: rebuild
          path: ./aoame/OntologyBasedModellingEnvironment-WebService/
    environment:
      - TRIPLESTORE_ENDPOINT=http://jena-fuseki:3030/ModEnv
    depends_on:
      - jena-fuseki
    ports:
      - 8080:8080
    networks:
      - aoame-network

  jena-fuseki:
    container_name: jena-fuseki-container
    build: ./aoame/fuseki-heroku-test
    #image: iisresearch/jena-fuseki-image:latest
    develop:
      watch:
        - action: rebuild
          path: ./aoame/fuseki-heroku-test/
    ports:
      - 3030:3030
    networks:
      - aoame-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3030" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  aoame-network:
    driver: bridge